In [4]:
import tensorflow as tf

if tf.__version__ < "2.0.0":
  !pip install --upgrade tensorflow_gpu==2.0

In [1]:
import tensorflow as tf

In [6]:
print(tf.__version__)

2.0.0


In [5]:
labels = [0,1,2,3,4,5,6,7,8,9]
tf.keras.utils.to_categorical(labels)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)

# STEP 1 : Loading Data
* The MNIST dataset comes preloaded in Keras, in the form of a set of four Numpy arrays.

* x_train and x_test parts contain greyscale RGB codes (from 0 to 255) .

* y_train and y_test parts contains labels from 0 to 9 which represents which number they actually are.

# 15/12/19

In [1]:
import numpy as np
x = [2,4,6,8]
y = [5,10,15,20]

# b = 0
# y = mx + b

m = (y[1]-y[0]) / (x[1]-x[0])
m

2.5

In [3]:
X = np.array ([2,4,6,8])
Y = np.array ([5,10,15,20])
M = Y/X
M

array([2.5, 2.5, 2.5, 2.5])

In [5]:
m = M.mean()
m

2.5

In [14]:
X = np.array ([1,2,3,4,5])
Y = np.array ([1,2,7,9,14])

M = Y/X
print("slope values = ", M, "\n--------------------------------------------------------------------------------------")

slope = M.mean()
print("average slope = ", slope, "\n--------------------------------------------------------------------------------------")

y = slope * x
print(y)

slope values =  [1.         1.         2.33333333 2.25       2.8       ] 
--------------------------------------------------------------------------------------
average slope =  1.8766666666666665 
--------------------------------------------------------------------------------------
[ 3.75333333  7.50666667 11.26       15.01333333]


In [ ]:
Function : Takes input from user, and returns output

# 5/1/2020

* when we compile tensor flow understands the data in the form of a graph for solving it, when the cod is executed
* tensor flow builds a model and an execution plan
* the processing starts when we run model fit

* tensor flow because of execution graph allows for parallel operations