1. load dataset
2. shuffle dataset
3. split training (70) validation (10) and test (20) %
4. split inputs and labels (output)
5. one hot coding
6. fit model without validation (compare training and testing accuracies)
7. fit model with validation (with history)
8. create graph
9. adjust epoch based on graph
10. check testing and training accuracies are matched or not

* (Chapter 3: Listing 3:17, 3:18, 3:19, 3:20)
* from tf.keras.utils import to_catagorical
* df.sample(frac = 1)
    * The frac keyword argument specifies trhe fraction of rows to return in the random sample, so frac = 1 means return all rows (in random order)

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder

In [2]:
from tensorflow import keras
layers = keras.layers
models = keras.models

In [60]:
# Step 1

df = pd.read_csv("datasets/sonar.csv")

df.head()

0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109  \
0  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
1  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
2  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
3  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
4  0.0286  0.0453  0.0277  0.0174  0.0384  0.0990  0.1201  0.1833  0.2105   

   0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084  \
0  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
1  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
2  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
3  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   
4  0.3039  ...  0.0045  0.0014  0.0038  0.0013  0.0089  0.0057  0.0027   

   0.0090  0.0032  R  
0  0.0052  0.0044  R  
1  0.0095  0.0078  R  
2  0.0040  0.0117  R  
3  0.0107  0.0094  R  
4  0.0051  0.0062  R  

[5 rows x 61 columns]

In [33]:
# Step 2

df = df.sample(frac = 1)
df.head()

0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109  \
137  0.0731  0.1249  0.1665  0.1496  0.1443  0.2770  0.2555  0.1712  0.0466   
199  0.0131  0.0387  0.0329  0.0078  0.0721  0.1341  0.1626  0.1902  0.2610   
148  0.0207  0.0535  0.0334  0.0818  0.0740  0.0324  0.0918  0.1070  0.1553   
32   0.0442  0.0477  0.0049  0.0581  0.0278  0.0678  0.1664  0.1490  0.0974   
205  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945   

     0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084  \
137  0.1114  ...  0.0444  0.0230  0.0290  0.0141  0.0161  0.0177  0.0194   
199  0.3193  ...  0.0150  0.0076  0.0032  0.0037  0.0071  0.0040  0.0009   
148  0.1234  ...  0.0033  0.0050  0.0190  0.0103  0.0121  0.0042  0.0090   
32   0.1268  ...  0.0204  0.0216  0.0135  0.0055  0.0073  0.0080  0.0105   
205  0.2354  ...  0.0086  0.0046  0.0126  0.0036  0.0035  0.0034  0.0079   

     0.0090  0.0032  R  
137  0.0207  0.0057  M  
199  0.0015  0.0085  M  
148  0.0070  0.0099  M  
32   0.0059  0.0105  R  
205  0.0036  0.0048  M  

[5 rows x 61 columns]

In [29]:
# Step 3

len(df)

207

In [30]:
training_data = df[:140]
training_data

0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109  \
31   0.0195  0.0213  0.0058  0.0190  0.0319  0.0571  0.1004  0.0668  0.0691   
76   0.0336  0.0294  0.0476  0.0539  0.0794  0.0804  0.1136  0.1228  0.1235   
166  0.0137  0.0297  0.0116  0.0082  0.0241  0.0253  0.0279  0.0130  0.0489   
153  0.0117  0.0069  0.0279  0.0583  0.0915  0.1267  0.1577  0.1927  0.2361   
155  0.0047  0.0059  0.0080  0.0554  0.0883  0.1278  0.1674  0.1373  0.2922   
72   0.0139  0.0222  0.0089  0.0108  0.0215  0.0136  0.0659  0.0954  0.0786   
163  0.0163  0.0198  0.0202  0.0386  0.0752  0.1444  0.1487  0.1484  0.2442   
28   0.0189  0.0308  0.0197  0.0622  0.0080  0.0789  0.1440  0.1451  0.1789   
148  0.0207  0.0535  0.0334  0.0818  0.0740  0.0324  0.0918  0.1070  0.1553   
121  0.0249  0.0119  0.0277  0.0760  0.1218  0.1538  0.1192  0.1229  0.2119   
191  0.0056  0.0267  0.0221  0.0561  0.0936  0.1146  0.0706  0.0996  0.1673   
161  0.0217  0.0152  0.0346  0.0346  0.0484  0.0526  0.0773  0.0862  0.1451   
154  0.0211  0.0128  0.0015  0.0450  0.0711  0.1563  0.1518  0.1206  0.1666   
116  0.0228  0.0106  0.0130  0.0842  0.1117  0.1506  0.1776  0.0997  0.1428   
185  0.0209  0.0191  0.0411  0.0321  0.0698  0.1579  0.1438  0.1402  0.3048   
142  0.0516  0.0944  0.0622  0.0415  0.0995  0.2431  0.1777  0.2018  0.2611   
150  0.0231  0.0315  0.0170  0.0226  0.0410  0.0116  0.0223  0.0805  0.2365   
195  0.0050  0.0017  0.0270  0.0450  0.0958  0.0830  0.0879  0.1220  0.1977   
25   0.0151  0.0320  0.0599  0.1050  0.1163  0.1734  0.1679  0.1119  0.0889   
119  0.0346  0.0509  0.0079  0.0243  0.0432  0.0735  0.0938  0.1134  0.1228   
5    0.0317  0.0956  0.1321  0.1408  0.1674  0.1710  0.0731  0.1401  0.2083   
42   0.0093  0.0269  0.0217  0.0339  0.0305  0.1172  0.1450  0.0638  0.0740   
182  0.0096  0.0404  0.0682  0.0688  0.0887  0.0932  0.0955  0.2140  0.2546   
92   0.0459  0.0437  0.0347  0.0456  0.0067  0.0890  0.1798  0.1741  0.1598   
104  0.0116  0.0179  0.0449  0.1096  0.1913  0.0924  0.0761  0.1092  0.0757   
38   0.0091  0.0213  0.0206  0.0505  0.0657  0.0795  0.0970  0.0872  0.0743   
26   0.0177  0.0300  0.0288  0.0394  0.0630  0.0526  0.0688  0.0633  0.0624   
187  0.0089  0.0274  0.0248  0.0237  0.0224  0.0845  0.1488  0.1224  0.1569   
108  0.0264  0.0071  0.0342  0.0793  0.1043  0.0783  0.1417  0.1176  0.0453   
78   0.0108  0.0086  0.0058  0.0460  0.0752  0.0887  0.1015  0.0494  0.0472   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
115  0.0094  0.0333  0.0306  0.0376  0.1296  0.1795  0.1909  0.1692  0.1870   
134  0.0094  0.0611  0.1136  0.1203  0.0403  0.1227  0.2495  0.4566  0.6587   
198  0.0116  0.0744  0.0367  0.0225  0.0076  0.0545  0.1110  0.1069  0.1708   
160  0.0305  0.0363  0.0214  0.0227  0.0456  0.0665  0.0939  0.0972  0.2535   
186  0.0368  0.0279  0.0103  0.0566  0.0759  0.0679  0.0970  0.1473  0.2164   
133  0.1083  0.1070  0.0257  0.0837  0.0748  0.1125  0.3322  0.4590  0.5526   
180  0.0423  0.0321  0.0709  0.0108  0.1070  0.0973  0.0961  0.1323  0.2462   
168  0.0130  0.0120  0.0436  0.0624  0.0428  0.0349  0.0384  0.0446  0.1318   
15   0.0352  0.0116  0.0191  0.0469  0.0737  0.1185  0.1683  0.1541  0.1466   
54   0.0201  0.0116  0.0123  0.0245  0.0547  0.0208  0.0891  0.0836  0.1335   
201  0.0272  0.0378  0.0488  0.0848  0.1127  0.1103  0.1349  0.2337  0.3113   
125  0.0715  0.0849  0.0587  0.0218  0.0862  0.1801  0.1916  0.1896  0.2960   
58   0.0125  0.0152  0.0218  0.0175  0.0362  0.0696  0.0873  0.0616  0.1252   
85   0.0188  0.0370  0.0953  0.0824  0.0249  0.0488  0.1424  0.1972  0.1873   
17   0.0270  0.0092  0.0145  0.0278  0.0412  0.0757  0.1026  0.1138  0.0794   
30   0.0084  0.0153  0.0291  0.0432  0.0951  0.0752  0.0414  0.0259  0.0692   
202  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328   
32   0.0442  0.0477  0.0049  0.0581  0.0278  0.0678  0.1664  0.1490  0.0974   
46   0.0373  0.0281  0.0232  0.0225  0.0179  0.0733  0.

In [45]:
# Step 4

training_data_input = training_data.iloc[:,:-1].values
training_data_input

array([[0.0195, 0.0213, 0.0058, ..., 0.0095, 0.0021, 0.0053],
       [0.0336, 0.0294, 0.0476, ..., 0.0015, 0.0069, 0.0051],
       [0.0137, 0.0297, 0.0116, ..., 0.0035, 0.0043, 0.0033],
       ...,
       [0.0209, 0.0261, 0.012 , ..., 0.0288, 0.0129, 0.0023],
       [0.0293, 0.0378, 0.0257, ..., 0.0055, 0.005 , 0.0087],
       [0.009 , 0.0062, 0.0253, ..., 0.0053, 0.0189, 0.0102]])

In [46]:
training_data_labels = training_data.iloc[:,-1:].values
training_data_labels

array([['R'],
       ['R'],
       ['M'],
       ['M'],
       ['M'],
       ['R'],
       ['M'],
       ['R'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['R'],
       ['M'],
       ['R'],
       ['R'],
       ['M'],
       ['R'],
       ['M'],
       ['R'],
       ['R'],
       ['M'],
       ['M'],
       ['R'],
       ['M'],
       ['R'],
       ['R'],
       ['R'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['R'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['R'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['M'],
       ['M'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['M'],
       ['R'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['R'],
      

In [63]:
# Step 5

encoder = LabelEncoder()
encoder.fit(training_data_labels)

encoded_training = encoder.transform(training_data_labels)
encoded_training

array([1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1])

In [57]:
validation_data = df[140:160]
validation_data

0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109  \
66   0.0368  0.0403  0.0317  0.0293  0.0820  0.1342  0.1161  0.0663  0.0155   
1    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
206  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843   
8    0.0164  0.0173  0.0347  0.0070  0.0187  0.0671  0.1056  0.0697  0.0962   
138  0.0164  0.0627  0.0738  0.0608  0.0233  0.1048  0.1338  0.0644  0.1522   
153  0.0117  0.0069  0.0279  0.0583  0.0915  0.1267  0.1577  0.1927  0.2361   
3    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
61   0.0086  0.0215  0.0242  0.0445  0.0667  0.0771  0.0499  0.0906  0.1229   
52   0.0293  0.0378  0.0257  0.0062  0.0130  0.0612  0.0895  0.1107  0.0973   
51   0.0087  0.0046  0.0081  0.0230  0.0586  0.0682  0.0993  0.0717  0.0576   
115  0.0094  0.0333  0.0306  0.0376  0.1296  0.1795  0.1909  0.1692  0.1870   
43   0.0257  0.0447  0.0388  0.0239  0.1315  0.1323  0.1608  0.2145  0.0847   
150  0.0231  0.0315  0.0170  0.0226  0.0410  0.0116  0.0223  0.0805  0.2365   
93   0.0025  0.0309  0.0171  0.0228  0.0434  0.1224  0.1947  0.1661  0.1368   
86   0.0856  0.0454  0.0382  0.0203  0.0385  0.0534  0.2140  0.3110  0.2837   
168  0.0130  0.0120  0.0436  0.0624  0.0428  0.0349  0.0384  0.0446  0.1318   
88   0.0235  0.0291  0.0749  0.0519  0.0227  0.0834  0.0677  0.2002  0.2876   
135  0.1088  0.1278  0.0926  0.1234  0.1276  0.1731  0.1948  0.4262  0.6828   
170  0.0179  0.0136  0.0408  0.0633  0.0596  0.0808  0.2090  0.3465  0.5276   
41   0.0211  0.0319  0.0415  0.0286  0.0121  0.0438  0.1299  0.1390  0.0695   

     0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084  \
66   0.0506  ...  0.0091  0.0160  0.0160  0.0081  0.0070  0.0135  0.0067   
1    0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
206  0.2354  ...  0.0146  0.0129  0.0047  0.0039  0.0061  0.0040  0.0036   
8    0.0251  ...  0.0090  0.0223  0.0179  0.0084  0.0068  0.0032  0.0035   
138  0.0780  ...  0.0258  0.0143  0.0226  0.0187  0.0185  0.0110  0.0094   
153  0.2169  ...  0.0053  0.0029  0.0020  0.0013  0.0029  0.0020  0.0062   
3    0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   
61   0.1185  ...  0.0072  0.0054  0.0022  0.0016  0.0029  0.0058  0.0050   
52   0.0751  ...  0.0065  0.0072  0.0108  0.0051  0.0102  0.0041  0.0055   
51   0.0818  ...  0.0052  0.0038  0.0079  0.0114  0.0050  0.0030  0.0064   
115  0.1725  ...  0.0153  0.0112  0.0241  0.0164  0.0055  0.0078  0.0055   
43   0.0561  ...  0.0096  0.0153  0.0096  0.0131  0.0198  0.0025  0.0199   
150  0.2461  ...  0.0125  0.0036  0.0123  0.0043  0.0114  0.0052  0.0091   
93   0.1430  ...  0.0149  0.0077  0.0036  0.0114  0.0085  0.0101  0.0016   
86   0.2751  ...  0.0172  0.0138  0.0079  0.0037  0.0051  0.0258  0.0102   
168  0.1375  ...  0.0084  0.0100  0.0018  0.0035  0.0058  0.0011  0.0009   
88   0.3674  ...  0.0083  0.0037  0.0095  0.0105  0.0030  0.0132  0.0068   
135  0.5761  ...  0.0455  0.0213  0.0082  0.0124  0.0167  0.0103  0.0205   
170  0.5965  ...  0.0123  0.0060  0.0187  0.0111  0.0126  0.0081  0.0155   
41   0.0568  ...  0.0090  0.0042  0.0153  0.0106  0.0020  0.0105  0.0049   

     0.0090  0.0032  R  
66   0.0078  0.0068  R  
1    0.0095  0.0078  R  
206  0.0061  0.0115  M  
8    0.0056  0.0040  R  
138  0.0078  0.0112  M  
153  0.0026  0.0052  M  
3    0.0107  0.0094  R  
61   0.0024  0.0030  R  
52   0.0050  0.0087  R  
51   0.0058  0.0030  R  
115  0.0091  0.0067  M  
43   0.0255  0.0180  R  
150  0.0008  0.0092  M  
93   0.0028  0.0014  R  
86   0.0037  0.0037  R  
168  0.0033  0.0026  M  
88   0.0108  0.0090  R  
135  0.0178  0.0187  M  
170  0.0160  0.0085  M  
41   0.0070  0.0080  R  

[20 rows x 61 columns]

In [64]:
validation_data_input = validation_data.iloc[:,:-1].values
validation_data_input

array([[0.0368, 0.0403, 0.0317, ..., 0.0067, 0.0078, 0.0068],
       [0.0262, 0.0582, 0.1099, ..., 0.0164, 0.0095, 0.0078],
       [0.026 , 0.0363, 0.0136, ..., 0.0036, 0.0061, 0.0115],
       ...,
       [0.1088, 0.1278, 0.0926, ..., 0.0205, 0.0178, 0.0187],
       [0.0179, 0.0136, 0.0408, ..., 0.0155, 0.016 , 0.0085],
       [0.0211, 0.0319, 0.0415, ..., 0.0049, 0.007 , 0.008 ]])

In [65]:
validation_data_labels = validation_data.iloc[:,-1:].values
validation_data_labels

array([['R'],
       ['R'],
       ['M'],
       ['R'],
       ['M'],
       ['M'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['M'],
       ['R'],
       ['M'],
       ['R'],
       ['R'],
       ['M'],
       ['R'],
       ['M'],
       ['M'],
       ['R']], dtype=object)

In [66]:
encoder.fit(validation_data_labels)

encoded_validation = encoder.transform(validation_data_labels)
encoded_validation

array([1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1])

In [58]:
testing_data = df[160:]
testing_data

0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109  \
7    0.0223  0.0375  0.0484  0.0475  0.0647  0.0591  0.0753  0.0098  0.0684   
23   0.0293  0.0644  0.0390  0.0173  0.0476  0.0816  0.0993  0.0315  0.0736   
12   0.0090  0.0062  0.0253  0.0489  0.1197  0.1589  0.1392  0.0987  0.0955   
42   0.0093  0.0269  0.0217  0.0339  0.0305  0.1172  0.1450  0.0638  0.0740   
142  0.0516  0.0944  0.0622  0.0415  0.0995  0.2431  0.1777  0.2018  0.2611   
193  0.0392  0.0108  0.0267  0.0257  0.0410  0.0491  0.1053  0.1690  0.2105   
171  0.0180  0.0444  0.0476  0.0698  0.1615  0.0887  0.0596  0.1071  0.3175   
95   0.0181  0.0146  0.0026  0.0141  0.0421  0.0473  0.0361  0.0741  0.1398   
110  0.0530  0.0885  0.1997  0.2604  0.3225  0.2247  0.0617  0.2287  0.0950   
155  0.0047  0.0059  0.0080  0.0554  0.0883  0.1278  0.1674  0.1373  0.2922   
92   0.0459  0.0437  0.0347  0.0456  0.0067  0.0890  0.1798  0.1741  0.1598   
9    0.0039  0.0063  0.0152  0.0336  0.0310  0.0284  0.0396  0.0272  0.0323   
117  0.0363  0.0478  0.0298  0.0210  0.1409  0.1916  0.1349  0.1613  0.1703   
123  0.0388  0.0324  0.0688  0.0898  0.1267  0.1515  0.2134  0.2613  0.2832   
72   0.0139  0.0222  0.0089  0.0108  0.0215  0.0136  0.0659  0.0954  0.0786   
126  0.0209  0.0261  0.0120  0.0768  0.1064  0.1680  0.3016  0.3460  0.3314   
111  0.0454  0.0472  0.0697  0.1021  0.1397  0.1493  0.1487  0.0771  0.1171   
152  0.0233  0.0394  0.0416  0.0547  0.0993  0.1515  0.1674  0.1513  0.1723   
65   0.0265  0.0440  0.0137  0.0084  0.0305  0.0438  0.0341  0.0780  0.0844   
83   0.0378  0.0318  0.0423  0.0350  0.1787  0.1635  0.0887  0.0817  0.1779   
13   0.0124  0.0433  0.0604  0.0449  0.0597  0.0355  0.0531  0.0343  0.1052   
201  0.0272  0.0378  0.0488  0.0848  0.1127  0.1103  0.1349  0.2337  0.3113   
47   0.0190  0.0038  0.0642  0.0452  0.0333  0.0690  0.0901  0.1454  0.0740   
125  0.0715  0.0849  0.0587  0.0218  0.0862  0.1801  0.1916  0.1896  0.2960   
175  0.0635  0.0709  0.0453  0.0333  0.0185  0.1260  0.1015  0.1918  0.3362   
53   0.0132  0.0080  0.0188  0.0141  0.0436  0.0668  0.0609  0.0131  0.0899   
189  0.0156  0.0210  0.0282  0.0596  0.0462  0.0779  0.1365  0.0780  0.1038   
45   0.0308  0.0339  0.0202  0.0889  0.1570  0.1750  0.0920  0.1353  0.1593   
68   0.0216  0.0215  0.0273  0.0139  0.0357  0.0785  0.0906  0.0908  0.1151   
187  0.0089  0.0274  0.0248  0.0237  0.0224  0.0845  0.1488  0.1224  0.1569   
29   0.0240  0.0218  0.0324  0.0569  0.0330  0.0513  0.0897  0.0713  0.0569   
156  0.0201  0.0178  0.0274  0.0232  0.0724  0.0833  0.1232  0.1298  0.2085   
188  0.0158  0.0239  0.0150  0.0494  0.0988  0.1425  0.1463  0.1219  0.1697   
77   0.0231  0.0351  0.0030  0.0304  0.0339  0.0860  0.1738  0.1351  0.1063   
40   0.0093  0.0185  0.0056  0.0064  0.0260  0.0458  0.0470  0.0057  0.0425   
114  0.0414  0.0436  0.0447  0.0844  0.0419  0.1215  0.2002  0.1516  0.0818   
31   0.0195  0.0213  0.0058  0.0190  0.0319  0.0571  0.1004  0.0668  0.0691   
67   0.0195  0.0142  0.0181  0.0406  0.0391  0.0249  0.0892  0.0973  0.0840   
76   0.0336  0.0294  0.0476  0.0539  0.0794  0.0804  0.1136  0.1228  0.1235   
18   0.0126  0.0149  0.0641  0.1732  0.2565  0.2559  0.2947  0.4110  0.4983   
116  0.0228  0.0106  0.0130  0.0842  0.1117  0.1506  0.1776  0.0997  0.1428   
105  0.0331  0.0423  0.0474  0.0818  0.0835  0.0756  0.0374  0.0961  0.0548   
157  0.0107  0.0453  0.0289  0.0713  0.1075  0.1019  0.1606  0.2119  0.3061   
78   0.0108  0.0086  0.0058  0.0460  0.0752  0.0887  0.1015  0.0494  0.0472   
204  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258   
143  0.0299  0.0688  0.0992  0.1021  0.0800  0.0629  0.0130  0.0813  0.1761   
181  0.0095  0.0308  0.0539  0.0411  0.0613  0.1039  0.1016  0.1394  0.2592   

     0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084  \
7    0.1487  ...  0.0145  0.0128  0.0145  0.0058  0.0049  0.0065  0.0093   
23   0.0860  ...  0.0035  0.0052  0.0083  0.0078  0.0075  0.

In [67]:
testing_data_input = testing_data.iloc[:,:-1].values
testing_data_input

array([[0.0223, 0.0375, 0.0484, ..., 0.0093, 0.0059, 0.0022],
       [0.0293, 0.0644, 0.039 , ..., 0.016 , 0.0095, 0.0011],
       [0.009 , 0.0062, 0.0253, ..., 0.0053, 0.0189, 0.0102],
       ...,
       [0.0522, 0.0437, 0.018 , ..., 0.0138, 0.0077, 0.0031],
       [0.0299, 0.0688, 0.0992, ..., 0.013 , 0.0115, 0.0015],
       [0.0095, 0.0308, 0.0539, ..., 0.003 , 0.0031, 0.0033]])

In [68]:
testing_data_labels = testing_data.iloc[:,-1:].values
testing_data_labels

array([['R'],
       ['R'],
       ['R'],
       ['R'],
       ['M'],
       ['M'],
       ['M'],
       ['R'],
       ['M'],
       ['M'],
       ['R'],
       ['R'],
       ['M'],
       ['M'],
       ['R'],
       ['M'],
       ['M'],
       ['M'],
       ['R'],
       ['R'],
       ['R'],
       ['M'],
       ['R'],
       ['M'],
       ['M'],
       ['R'],
       ['M'],
       ['R'],
       ['R'],
       ['M'],
       ['R'],
       ['M'],
       ['M'],
       ['R'],
       ['R'],
       ['M'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['M'],
       ['M'],
       ['M'],
       ['R'],
       ['M'],
       ['M'],
       ['M']], dtype=object)

In [70]:
encoder.fit(testing_data_labels)

encoded_testing = encoder.transform(testing_data_labels)
encoded_testing

array([1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0])

In [ ]:
epoch = 80
model = models.Sequential()
model.add(layers.Dense(32, activation='relu', input_shape=(60,)))
model.add(layers.Dense(16, activation='relu'))
model.add(layers.Dense(1, activation='sigmoid'))