In [2]:
from PIL import Image
import glob
import numpy as np

image_list = []
resized_images = []


# reading images from folder
for filename in glob.glob(r'photos\*.jpg'):
    img = Image.open(filename)                                           #variable for images
    image_list.append(img)                                               # appending images to a list
        

# resizing images        
for image in image_list:                                                
    res = image.resize((200, 200))
    resized_images.append(res)                                           # appending resized images to another list 

    
mainarray = np.zeros([20, 200, 200, 3])                            # making the main array


i = 0
n = 0
for (i,new ) in enumerate(resized_images):
    img = np.array(new)
    mainarray[n] = img[:, :, :3]                                  # inserting image array in main array
    n = n + 1

    
    
print(mainarray)


[[[[  0.  25.  65.]
   [  2.  25.  67.]
   [  1.  24.  66.]
   ...
   [ 28.  33.  71.]
   [ 28.  36.  73.]
   [ 29.  34.  72.]]

  [[  4.  27.  68.]
   [  2.  26.  70.]
   [  2.  26.  70.]
   ...
   [ 30.  32.  71.]
   [ 31.  39.  76.]
   [ 28.  35.  77.]]

  [[  2.  30.  70.]
   [  2.  26.  70.]
   [  0.  24.  68.]
   ...
   [ 35.  37.  76.]
   [ 35.  37.  76.]
   [ 37.  38.  82.]]

  ...

  [[  8.  21.  29.]
   [  4.  18.  27.]
   [  7.  22.  29.]
   ...
   [ 46.  26.  27.]
   [ 35.  24.  28.]
   [ 25.  20.  26.]]

  [[  1.  18.  26.]
   [  4.  21.  29.]
   [ 10.  25.  28.]
   ...
   [ 66.  28.  25.]
   [ 28.  17.  15.]
   [ 20.  16.  13.]]

  [[  4.  21.  29.]
   [  6.  20.  29.]
   [ 11.  22.  24.]
   ...
   [149.  41.   3.]
   [ 71.  25.   9.]
   [ 31.  18.  10.]]]


 [[[144.  78.  46.]
   [153.  89.  54.]
   [137.  76.  47.]
   ...
   [ 34.  19.  12.]
   [ 21.  20.  18.]
   [ 21.  13.  10.]]

  [[130.  69.  38.]
   [140.  77.  46.]
   [120.  63.  34.]
   ...
   [ 21.  17.  16.]
 