In [1]:
import numpy as np

# 1D Array

In [10]:
# create 1D Array
a = np.array([1,2,3,4,5,6])
#             0,1,2,3,4,5  Index Number 
a

array([1, 2, 3, 4, 5, 6])

# Indexing In 1D Array

In [5]:
# Access an element with indexing
#arrayName[index number]
a[5] #6

6

In [11]:
a[3] # 4

4

# Slicing in 1D Array

In [12]:
#arrayName[startIndex : Ending Index+1] Ending Index is Not Included that's why ending Index+1
a[0:4]

array([1, 2, 3, 4])

In [13]:
a[1:2]

array([2])

# 2D Array 

2D Array is just like a simple matrix

In [2]:
array_2D = np.array([[1,2,3],[4,5,6]])
array_2D
# A matrix have 3 rows and 3columns

array([[1, 2, 3],
       [4, 5, 6]])

# Indexing in 2D Array

In [26]:
# Indexing in 2D Arrays
# arrayName[rowNumber][element Index]
print("0 row 1 index element: ")
print(array_2D[0][1]) # 2
print("1 row 2 index element: ")
print(array_2D[1][2])



0 row 1 index element: 
2
1 row 2 index element: 
6


# Slicing in 2D Array

1.Access Elements in 2D Array

2.Access specific row or specific Column in 2D Array

In [28]:
array_2D # it is define Above (In [17])

array([[1, 2, 3],
       [4, 5, 6]])

1.Access Elements in 2D Array

In [31]:
# Print specific Element
array_2D[1,1] # first row(row strat with 0 index) first index Element

5

In [32]:
array_2D[0,2]# 0th  row(row strat with 0 index) second index Element

3

2.Access specific or specific Column in 2D Array

In [38]:
# Specific Rows
print(array_2D[0]) #First Row (Index 0)
print(array_2D[1]) #Second Row (Index 1)



[1 2 3]
[4 5 6]


In [29]:
# case 1: We have to print 2nd column
# arrayName[row:column]
array_2D[:,1] # [row: , :column] empty : means all rows and [1,:] means all columns

array([2, 5])

In [3]:
# case 2: we have to print 1st 3rd column

array_2D[: , 2]

array([3, 6])

# 3D Array

In [4]:
# create 3D Array
array_3D = np.array([[[1,2,3] , [4, 5 , 6] , [7, 8, 9]] , 
                     [[10 ,11, 12] , [13, 14, 15] , [16 , 17 ,18]], 
                     [[19,20,21] , [22,23,24] , [25,26,27]]])
array_3D

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

# Indexing in 3D Array

In [15]:
# In 3D array every set has an index number
array_3D[1]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

# Slicing in 3D array

In [6]:
# Case 1: we have to print 5 from first set
array_3D[0,1,1]

5

In [7]:
# Case 2: We have to print 2nd column of the second Matrix
array_3D[1,:,1]

array([11, 14, 17])

In [17]:
# Case 3: we have to print 1st 2 elements of the 2nd row of 2nd set
array_3D[1,1,0:2]

array([13, 14])

In [20]:
# Case 3: We have to print all columns of 3D Matrix
array_3D[:,:,1]

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])

In [22]:
# Case 4: we have to print all 3rd elemnt of 2nd row of all sets
array_3D[:,1,2]

array([ 6, 15, 24])

# Reshape Array in Numpy

what Does Reshape means?

reshape means you reshape the 1D array in to 2D or change rows and Columns

For reshaping it is compulsory to store the reshape dimentions into a variable Otherwise it doesnot change the dimention

In [1]:
import numpy as np

# We write an array

a = np.array([[1 ,2, 3, 4 ,5], [6 , 7 , 8 , 9 , 10]])
print(a.shape) #Find the shape of the array ( rows ,columns)
# now we reshape 2 x 5 in to multiple ways
a = a.reshape(5,2) # 5 rows and 2 columns
print(a)


(2, 5)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [2]:
x = np.zeros((2,6))
print(x)# An array of zeros with 2 rows and 6 columns

print("\nShape of array: ")

print(x.shape)
print("\nReshape: 1 row 12 columns")
y = x.reshape(1, 12)
print(y)


print("\nReshape: 6 row 2 columns")
y = x.reshape(6, 2)
print(y)


print("\nReshape: A 3D Array of 2 plains , 3 rows and 12 columns")
y = x.reshape(2,3,2)
print(y)


print("\nReshape: 3 Plains 2 rows 2 columns")
y = x.reshape(3,2,2)
print(y)


print("\nReshape: 2 Plains 2 rows 3 columns")
y = x.reshape(2,2,3)
print(y)


print("\nReshape: 4 Plains 1 rows 3 columns")
y = x.reshape(4,1,3)
print(y)

print("\nReshape: 6 Plains 1 rows 2 columns")
y = x.reshape(6,1,2)
print(y)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

Shape of array: 
(2, 6)

Reshape: 1 row 12 columns
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

Reshape: 6 row 2 columns
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

Reshape: A 3D Array of 2 plains , 3 rows and 12 columns
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]

Reshape: 3 Plains 2 rows 2 columns
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]

Reshape: 2 Plains 2 rows 3 columns
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]

Reshape: 4 Plains 1 rows 3 columns
[[[0. 0. 0.]]

 [[0. 0. 0.]]

 [[0. 0. 0.]]

 [[0. 0. 0.]]]

Reshape: 6 Plains 1 rows 2 columns
[[[0. 0.]]

 [[0. 0.]]

 [[0. 0.]]

 [[0. 0.]]

 [[0. 0.]]

 [[0. 0.]]]


# Neagative Values in Reshape


It simply Ignores the negative value

In [3]:
x = np.zeros((2,6))
print(x)

y = x.reshape(1, -12) #It ignores the Negative sign and print matrix 1 row 1 columns
print(y)

y = x.reshape(3,2,-2) #It ignores the Negative sign and print matrix 3 plains 2 row 2 columns
print(y)





[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
