In [ ]:
numerical python = python advanced library
we have facilities for numerical computing
we have options for matrix multiplication and manipulation

every data in numpy is stored in ndarray
fast operations on entire arrrays is possible with it
we can add multiply and divide several arrays

we have reading and writing facilities
linear algebra operations are possible with matrices in single line of code

data in numpy is stored in contigous block of memory(in series)
numpy arrays are faster than python sequences(dynamic arrays)

complex computation on entire arrays

pip == python package installer
pip install numpy === to install library

# List is slower


In [7]:
#making a list of 1 million numbers
l = range(1000000)

# multiplying each number of list by 2    ||   10 times
%time for i in range(1, 10): r = [x * 2 for x in l]

Wall time: 1.56 s


# Numpy array is 100 times faster

In [8]:
import numpy as np

# Making an array of 1 million number
d = np.arange (1000000)

# multiplying array by 2                   ||   10 times
%time for i in range(1, 10): r = d * 2

Wall time: 43.1 ms


In [ ]:
Attributer of Numpy
everything is stored in ndarray internally in numpy

# Multidimensional Array Object

In [27]:
#  Every thing in numpy is internally stored in ndarray
#              ndarray can be of one or any other required dimensions
import numpy as np

# tuple tells the size of the array
x = np.zeros((4, 4))           #numpy array with all zero element, size of the array specified by tuple

x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.ones((5,5))             #numpy array with all one elements


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
np.empty ((3, 3))          # numpy array with garbage data

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 5.75092412e-321],
       [8.45603440e-307, 1.24611470e-306, 6.95233839e-310]])

# Passing a list elements into a numpy array

In [33]:
l = [1, 4, 5, 6]

np.array(l)

array([1, 4, 5, 6])

In [37]:
x = np.arange(1, 100, 10)          # an array with a given range of numbers with step size
#         start  end   step size

print (x)

# to check the shape of the array
x.shape

[ 1 11 21 31 41 51 61 71 81 91]


(10,)

In [51]:
# showing shape of array
y = np.zeros((10, 10))

print(y)

# array of 10 * 10 = 100 elements
y.shape

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


(10, 10)

In [46]:
# reshape an array
y = y.reshape((2, 2, 5, 5))

y

# number of elements should remain same

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [47]:
# see data type of an array
y.dtype

dtype('float64')

In [49]:
# to see dimensions of array
y.ndim

# data type can be of any type

4

# Arithmatic with nd-array

#### Add two arrays === vectorization

In [9]:
import numpy as np

# making a random array of 10 elements
a = np.random.randn((10))
a

array([-0.18972441,  2.92561234,  0.10499755, -1.78169643, -0.54471481,
        0.72332671, -0.43434509, -0.84338713, -0.74545333, -1.06540045])

In [10]:
b = np.random.randn((10))
b

array([ 0.44133837, -0.14286365,  0.59000987,  0.90897371,  1.15101728,
        1.02429854,  1.35305699, -0.46865521, -0.652758  ,  1.05991694])

In [11]:
#adding them (not possible in list)
a + b

array([ 0.25161396,  2.78274869,  0.69500743, -0.87272272,  0.60630247,
        1.74762525,  0.9187119 , -1.31204233, -1.39821133, -0.00548351])

In [12]:
#subtracting them
a - b

array([-0.63106278,  3.06847599, -0.48501232, -2.69067014, -1.6957321 ,
       -0.30097183, -1.78740208, -0.37473192, -0.09269533, -2.1253174 ])

In [13]:
# multiplying array by 2
a * 2

array([-0.37944882,  5.85122468,  0.20999511, -3.56339286, -1.08942963,
        1.44665341, -0.86869019, -1.68677425, -1.49090666, -2.13080091])

In [15]:
# inversing it
1 / a

array([-5.27080304,  0.34180879,  9.52403144, -0.56126284, -1.83582303,
        1.38250114, -2.30231679, -1.18569512, -1.3414656 , -0.9386142 ])

In [16]:
# boolean for condition
a > 0

array([False,  True,  True, False, False,  True, False, False, False,
       False])

In [17]:
# passing boolean as index to show elements for condition
a [a > 0]

array([2.92561234, 0.10499755, 0.72332671])

# Indexing and Slicing
similar to python list

In [18]:
import numpy as np

#creating an array from list
q = np.array([1,7,9,8,5])

# index       0,1,2,3,4

In [22]:
# getting element from index number

q[1]

7

In [25]:
#boolean indexing
q[q > 4]

array([7, 9, 8, 5])

In [27]:
#fancy indexing
q [[2, 1]]

# takes elemets from 1 and 2 index

array([9, 7])

In [29]:
# random array of required dimension
z = np.random.randn(10, 10)
z

array([[ 0.12587613,  0.31835299,  0.22250688,  0.7231438 ,  0.76976595,
         1.51194323, -1.60241591, -1.18695469,  0.93017361,  0.14641115],
       [-0.23792751,  0.58862304,  1.54994349,  0.18384471,  0.84668657,
         0.00663759,  0.27622655,  0.55827396,  1.09141822, -0.43692309],
       [-0.01942059,  0.60195429,  0.83758826, -1.14572964,  0.93678933,
         2.33444765,  0.25552037,  0.4172091 ,  1.7030225 ,  0.56878071],
       [-0.19329392, -0.67717913, -1.19226244,  1.18997176, -0.62601431,
         0.24527936, -0.1409028 ,  0.66836905,  0.23990476,  1.51447828],
       [-0.48774144,  0.82059004,  0.46273666, -0.67111306,  0.31325162,
         0.53610503, -1.10866234,  2.59628707, -0.46258946,  2.20850029],
       [ 0.63591283,  0.14778416,  1.69974551,  0.12769736,  0.08854732,
         0.92623837,  0.4170686 , -1.15008461,  1.93777143, -0.75339934],
       [ 1.43045736, -1.09447543,  0.27286145, -0.11313869,  0.83372583,
        -0.28945605,  2.25906906,  0.77452958

In [30]:
# picking 1st row
z [0]

array([ 0.12587613,  0.31835299,  0.22250688,  0.7231438 ,  0.76976595,
        1.51194323, -1.60241591, -1.18695469,  0.93017361,  0.14641115])

In [32]:
# taking 5th column of 1st row
z [0][4]

0.7697659506318605

In [41]:
# for odd rows in the array
# from 1st to 10th row, and every 2nd row 
z [1:10:2,::]

# for all columns

array([[-0.23792751,  0.58862304,  1.54994349,  0.18384471,  0.84668657,
         0.00663759,  0.27622655,  0.55827396,  1.09141822, -0.43692309],
       [-0.19329392, -0.67717913, -1.19226244,  1.18997176, -0.62601431,
         0.24527936, -0.1409028 ,  0.66836905,  0.23990476,  1.51447828],
       [ 0.63591283,  0.14778416,  1.69974551,  0.12769736,  0.08854732,
         0.92623837,  0.4170686 , -1.15008461,  1.93777143, -0.75339934],
       [-0.0180915 , -0.49299202,  1.85934212, -0.73860656, -1.11062399,
        -2.70990613, -0.73399204,  0.02939444, -0.18672102, -0.54263688],
       [-0.39305242,  0.37467738, -1.04055133,  1.19152586,  1.22628769,
         0.61658785, -1.11465497,  0.1747176 ,  1.59298362,  0.65413442]])

In [43]:
# for slicing the first 4 columns, and all rows
z[::, 0:4]

array([[ 0.12587613,  0.31835299,  0.22250688,  0.7231438 ],
       [-0.23792751,  0.58862304,  1.54994349,  0.18384471],
       [-0.01942059,  0.60195429,  0.83758826, -1.14572964],
       [-0.19329392, -0.67717913, -1.19226244,  1.18997176],
       [-0.48774144,  0.82059004,  0.46273666, -0.67111306],
       [ 0.63591283,  0.14778416,  1.69974551,  0.12769736],
       [ 1.43045736, -1.09447543,  0.27286145, -0.11313869],
       [-0.0180915 , -0.49299202,  1.85934212, -0.73860656],
       [ 0.32815426,  0.62351883, -0.2110366 ,  0.07459151],
       [-0.39305242,  0.37467738, -1.04055133,  1.19152586]])

In [45]:
# for square shape with 1s on border
c = np.ones((5,5))
c

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [47]:
# to make sides 0
c[1:-1,1:-1] = 0
c

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# Fast element wise array operation

In [50]:
import numpy as np

x = np.array([10,9,8,6,11])
x

array([10,  9,  8,  6, 11])

In [51]:
#For square roor of whole array
np.sqrt(x)

array([3.16227766, 3.        , 2.82842712, 2.44948974, 3.31662479])

In [52]:
#for power on array elements
np.power(x,2)

array([100,  81,  64,  36, 121], dtype=int32)

In [53]:
y = [7,1,2,3,-1]

In [54]:
# to get maximum values between arrays, element wise
np.maximum(x,y)

array([10,  9,  8,  6, 11])

# Turnary Operators

#### Condition, Exp1, Exp 2
         True , Fasle

### turnary operator where is applied to the whole array

#### It is used for data filtering and data processing

In [3]:
import numpy as np
salary = np.array([0, -1, 100000, 50000])

#          if       do this    otherwise, let it be
np.where(salary<=0, 25000, salary)

array([ 25000,  25000, 100000,  50000])

In [4]:
np.where(salary<=0, "Nok OK", "Ok")

array(['Nok OK', 'Nok OK', 'Ok', 'Ok'], dtype='<U6')

# Mathematical & Statistical Methods

##### Numpy has methematical functions for different operation
Some Methods work on boolean arrays

In [5]:
import numpy as np

x = np.array([10,9,7,10,7])

In [6]:
# for sum of elements
x.sum()

43

In [8]:
#for mean of elements
x.mean()

8.6

In [9]:
#for cummalative sum of elements
x.cumsum()

array([10, 19, 26, 36, 43], dtype=int32)

In [10]:
#for cummalative product of elements
x.cumprod()

array([   10,    90,   630,  6300, 44100], dtype=int32)

In [16]:
#to return boolean array
y = x > 7
y

array([ True,  True, False,  True, False])

In [18]:
#to sum true of these booleans
y.sum()

3

In [20]:
#to check if any element is true
y.any()

True

In [21]:
#to check if all are true
y.all()

False

In [22]:
#to sort the array
x.sort()
x

array([ 7,  7,  9, 10, 10])

In [23]:
#to check unique elements in array
np.unique(x)

array([ 7,  9, 10])

# File Reading And Writing
We can save and load multiple arrays to files|

np.save(filename.npy, array)  [if EXT is not given if gives if automatically]

np.load(filename.npy) [returns a dictionary if loading a .npz d file to retrieve values through keys]

np.savez(filename.npz, array1, array2)

In [44]:
import numpy as np

x = [1,4,5,7]
y = [8,7,9]

In [45]:
np.save('testx', x)

In [46]:
loadx = np.load('testx.npy') 
loadx

array([1, 4, 5, 7])

In [56]:
#to store multiple elements
np.savez('testxy',x,y)

In [57]:
loadxy = np.load('testxy.npz')
loadxy

In [59]:
loadxy['x']

KeyError: 'x is not a file in the archive'

# Linear Algebra Functions
for operations with matrices

In [60]:
import numpy as np

x = np.random.randn(3,2)

y = np.random.randn(2,3)

In [61]:
# for dot product

x.dot(y)

array([[ 0.01628439, -0.925162  ,  0.90660008],
       [ 1.98117599,  0.21655758, -0.33104447],
       [ 0.52760438,  0.10885229, -0.1383682 ]])

In [62]:
# for transpose of matrix
x.transpose()

array([[-1.6112618 , -0.1131786 ,  0.05877405],
       [-1.28832371,  1.95286074,  0.5920849 ]])

In [64]:
#to get the trace of a matrix
x.trace()

0.34159893092720583

# Pseudo Random Number Generator

when working with data science libraries or machine learning 
when we load our dataset, we need to randomize our data to remove biasness from the data

computer generates a random number through algorithims or different distributions
We need initialize the generator (seed value) to generate the random number

In [67]:
import numpy as np

# giving a seed value
np.random.seed(7)

# now generating random number by normal distribution
np.random.normal(size = (3,3))

array([[ 1.69052570e+00, -4.65937371e-01,  3.28201637e-02],
       [ 4.07516283e-01, -7.88923029e-01,  2.06557291e-03],
       [-8.90385858e-04, -1.75472431e+00,  1.01765801e+00]])

In [68]:
# now generating random number by uniform distribution

np.random.uniform(size = (3,3))

array([[0.38094113, 0.06593635, 0.2881456 ],
       [0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892]])

# Numpy Advanced Array Manipulation

## Reshape Method 
number of elements must remain same

row major order and column major order are internally data storage orders of arrays|

In [ ]:
'C' ORDER = row major order (horizontal storage)
'F' ORDER = column major order (vertical storage)

we can skip any dimension or specify -1
flatening = to reshape array into single dimension

In [70]:
 import numpy as np
    
x = np.random.randn(4,5)

x

array([[-1.2528644 , -0.68676875, -2.17661468, -0.63911575,  1.61103837],
       [-0.50541495,  1.56990122,  1.90816149, -1.0443414 , -2.54435423],
       [ 0.68474604,  0.21465687,  1.84624536,  0.16640132,  0.07166549],
       [-0.34571734,  0.1415094 ,  0.80677723, -1.66546597,  1.22570438]])

In [71]:
# saves in row major order by default
x.reshape(2,2,5)

array([[[-1.2528644 , -0.68676875, -2.17661468, -0.63911575,
          1.61103837],
        [-0.50541495,  1.56990122,  1.90816149, -1.0443414 ,
         -2.54435423]],

       [[ 0.68474604,  0.21465687,  1.84624536,  0.16640132,
          0.07166549],
        [-0.34571734,  0.1415094 ,  0.80677723, -1.66546597,
          1.22570438]]])

In [72]:
# to reshape into column major order
x.reshape((2,2,5),order = 'F')

array([[[-1.2528644 , -0.68676875, -2.17661468, -0.63911575,
          1.61103837],
        [ 0.68474604,  0.21465687,  1.84624536,  0.16640132,
          0.07166549]],

       [[-0.50541495,  1.56990122,  1.90816149, -1.0443414 ,
         -2.54435423],
        [-0.34571734,  0.1415094 ,  0.80677723, -1.66546597,
          1.22570438]]])

In [73]:
# to skip one dimesion
x.reshape((2,2,-1))

array([[[-1.2528644 , -0.68676875, -2.17661468, -0.63911575,
          1.61103837],
        [-0.50541495,  1.56990122,  1.90816149, -1.0443414 ,
         -2.54435423]],

       [[ 0.68474604,  0.21465687,  1.84624536,  0.16640132,
          0.07166549],
        [-0.34571734,  0.1415094 ,  0.80677723, -1.66546597,
          1.22570438]]])

In [75]:
# for flatening(convert into one dimension)
x.ravel() 

array([-1.2528644 , -0.68676875, -2.17661468, -0.63911575,  1.61103837,
       -0.50541495,  1.56990122,  1.90816149, -1.0443414 , -2.54435423,
        0.68474604,  0.21465687,  1.84624536,  0.16640132,  0.07166549,
       -0.34571734,  0.1415094 ,  0.80677723, -1.66546597,  1.22570438])

In [76]:
x.flatten()

array([-1.2528644 , -0.68676875, -2.17661468, -0.63911575,  1.61103837,
       -0.50541495,  1.56990122,  1.90816149, -1.0443414 , -2.54435423,
        0.68474604,  0.21465687,  1.84624536,  0.16640132,  0.07166549,
       -0.34571734,  0.1415094 ,  0.80677723, -1.66546597,  1.22570438])

# Concatenate

### takes a set of arrays and concatenates row wise or column wise

###### takes the axis to determine row wise or column wise concatenation
###### if axis=0 ,row wise concatenation
###### if axis=1 ,column wise concatenation

## Convenience functions
##### vstack = row wise concatenation
##### hstack = column wise concatenation

In [1]:
import numpy as np

# making a list
x = [[1,3,5],[7,9,0]]

# converting to array
arr1 = np.array(x)

# making a list
y = [[11,13,15],[17,19,10]]

# converting to array
arr2 = np.array(y)

In [3]:
# row wise concatenation
np.concatenate((arr1,arr2), axis=0)

array([[ 1,  3,  5],
       [ 7,  9,  0],
       [11, 13, 15],
       [17, 19, 10]])

In [4]:
# column wise concatenation
np.concatenate((arr1,arr2), axis=1)

array([[ 1,  3,  5, 11, 13, 15],
       [ 7,  9,  0, 17, 19, 10]])

In [7]:
# row wise concatenation
np.vstack((arr1,arr2))

array([[ 1,  3,  5],
       [ 7,  9,  0],
       [11, 13, 15],
       [17, 19, 10]])

In [8]:
# column wise concatenation
np.hstack((arr1,arr2))

array([[ 1,  3,  5, 11, 13, 15],
       [ 7,  9,  0, 17, 19, 10]])

# split
### complimentary method
##### breaks an array into multiples from specified positions

In [9]:
import numpy as np

x = [1,4,5,6,7,9,1,4]

d = np.array(x)

np.split(d,[2,5])
#           positions to split

[array([1, 4]), array([5, 6, 7]), array([9, 1, 4])]

In [13]:
y = [1,4,5,6,7,9,1,4],
[11,14,15,16,17,19,11,14]

d = np.array(y)

#split along y-axis
np.split(d,[4,6],axis=1)

[array([[1, 4, 5, 6]]), array([[7, 9]]), array([[1, 4]])]

In [15]:
#split along x-axis
np.split(d,[1],axis=0)

[array([[1, 4, 5, 6, 7, 9, 1, 4]]), array([], shape=(0, 8), dtype=int32)]

# Tile And Repeat

###### repeat takes an array and repeats the elements specified number of times

###### tile repeats or tiles the whole array

In [17]:
import numpy as np

d = np.array([1,5,7,8])

In [18]:
np.repeat(d, 3)

array([1, 1, 1, 5, 5, 5, 7, 7, 7, 8, 8, 8])

In [19]:
np.tile(d,2)

array([1, 5, 7, 8, 1, 5, 7, 8])

### smaller array expands itself === broadcasting